import os

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_TOKEN")
API_BASE_URL = "http://fastapi:8000"
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = int(os.getenv("REDIS_PORT",6379))
DB_NUM_CACHE_GROUP_ID = 1
DB_NUM_CACHE_EXPENSE_ID = 2
